version: '3.3'
services:
  pgadmin:
      image: dpage/pgadmin4
      environment:
          -  PGADMIN_DEFAULT_EMAIL=agencia@automatizatech.com
          -  PGADMIN_DEFAULT_PASSWORD=typebot
      ports:
          - "5050:80" 
