version: '3.3'
services:
  caddy-gen:
    image: 'wemakeservices/caddy-gen:latest'
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - typebot-builder
      - typebot-viewer
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot 
      - POSTGRES_PASSWORD=typebot 
  typebot-builder:
    labels:
      virtual.host: 'typebot.automatizatech.com' # change domain
      virtual.port: '3000'
      virtual.tls-email: 'agencia@automatizatech.com' 
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebot.automatizatech.com # change domain
      - NEXT_PUBLIC_VIEWER_URL=https://chat.automatizatech.com # change domain
      - ENCRYPTION_SECRET=L93ucM65LzmKV2rzwyHCkwt8c9/+Kxz9
      - ADMIN_EMAIL=agencia@automatizatech.com
      - DISABLE_SIGNUP=false
      - SMTP_AUTH_DISABLED=false
      - SMTP_SECURE=true 
      - SMTP_HOST=smtp.ionos.es 
      - SMTP_PORT=587
      - SMTP_USERNAME=agencia@automatizatech.com 
      - SMTP_PASSWORD=C6&eLSz&0o
      - SMTP_FROM_ADDRESS=agencia@automatizatech.com
      - NEXT_PUBLIC_SMTP_FROM=agencia@automatizatech.com
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storage.automatizatech.com # change domain
  typebot-viewer:
    labels:
      virtual.host: 'chat.automatizatech.com' # change domain
      virtual.port: '3000'
      virtual.tls-email: 'agencia@automatizatech.com' 
    image: baptistearno/typebot-viewer:latest
    restart: always
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebot.automatizatech.com # change domain
      - NEXT_PUBLIC_VIEWER_URL=https://chat.automatizatech.com # change domain
      - ENCRYPTION_SECRET=L93ucM65LzmKV2rzwyHCkwt8c9/+Kxz9
      - SMTP_HOST=smtp.ionos.es 
      - NEXT_PUBLIC_SMTP_FROM=agencia@automatizatech.com 
      - S3_ACCESS_KEY=minio 
      - S3_SECRET_KEY=minio123 
      - S3_BUCKET=typebot
      - S3_ENDPOINT=18.101.23.33 # change domain
  mail:
    image: bytemark/smtp
    restart: always
  minio:
    labels:
      virtual.host: 'storage.automatizatech.com' # change domain
      virtual.port: '9000'
      virtual.tls-email: 'agencia@automatizatech.com' 
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio 
      MINIO_ROOT_PASSWORD: minio123 
    volumes:
      - s3_data:/data
  # This service just make sure a bucket with the right policies is created

  # Certifique-se de atualizar S3_ACCESS_KEY , S3_SECRET_KEY abaixo para corresponder às suas configurações do S3, elas estão no final dessa linha /usr/bin/mc config host add minio http://minio:9000 minio minio123; sendo o usuario e a senha em sequencia.
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "
volumes:
  db_data:
  s3_data:
  caddy-certificates:
    driver: local
